/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'media',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './lib/**/*.{js,jsx,ts,tsx}',
    './providers/**/*.{js,jsx,ts,tsx}',
    './constants/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#f9fafb',
        foreground: '#111827',
        card: '#ffffff',
        'card-foreground': '#111827',
        popover: '#ffffff',
        'popover-foreground': '#111827',
        primary: '#1e3a8a',
        'primary-foreground': '#f9fafb',
        secondary: '#3b82f6',
        'secondary-foreground': '#f8fafc',
        accent: '#6d28d9',
        'accent-foreground': '#f5f3ff',
        muted: '#f3f4f6',
        'muted-foreground': '#4b5563',
        destructive: '#dc2626',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#2563eb',
        'chart-2': '#16a34a',
        'chart-3': '#f59e0b',
        'chart-4': '#0ea5e9',
        'chart-5': '#6d28d9',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#111827',
        'sidebar-primary': '#1e3a8a',
        'sidebar-primary-foreground': '#f9fafb',
        'sidebar-accent': '#3b82f6',
        'sidebar-accent-foreground': '#f8fafc',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#3b82f6',
        // Dark counterparts (use with `dark:` or explicit class names)
        'background-dark': '#0f172a',
        'foreground-dark': '#e5e7eb',
        'card-dark': '#111827',
        'card-foreground-dark': '#e5e7eb',
        'popover-dark': '#111827',
        'popover-foreground-dark': '#e5e7eb',
        'primary-dark': '#60a5fa',
        'primary-foreground-dark': '#0b1220',
        'secondary-dark': '#2563eb',
        'secondary-foreground-dark': '#e5e7eb',
        'accent-dark': '#a855f7',
        'accent-foreground-dark': '#f8fafc',
        'muted-dark': '#1f2937',
        'muted-foreground-dark': '#9ca3af',
        'destructive-dark': '#ef4444',
        'border-dark': '#1f2937',
        'input-dark': '#1f2937',
        'ring-dark': '#60a5fa',
        'chart-1-dark': '#60a5fa',
        'chart-2-dark': '#22c55e',
        'chart-3-dark': '#facc15',
        'chart-4-dark': '#38bdf8',
        'chart-5-dark': '#8b5cf6',
        'sidebar-dark': '#0f172a',
        'sidebar-foreground-dark': '#e5e7eb',
        'sidebar-primary-dark': '#60a5fa',
        'sidebar-primary-foreground-dark': '#0b1220',
        'sidebar-accent-dark': '#2563eb',
        'sidebar-accent-foreground-dark': '#e5e7eb',
        'sidebar-border-dark': '#1f2937',
        'sidebar-ring-dark': '#60a5fa',
      },
      borderRadius: {
        none: 0,
        DEFAULT: 10,
        sm: 6,
        md: 8,
        lg: 10,
        xl: 14,
        '2xl': 16,
        full: 9999,
      },
    },
  },
  plugins: [],
};
